// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | QuoteBlockSlice
  | ClientsBlockSlice
  | TeamBlockSlice
  | IntroBlockSlice
  | HeaderBlockSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Clients → Items*
 */
export interface ClientsDocumentDataItemsItem {
  /**
   * Logo field in *Clients → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *Clients → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * URL field in *Clients → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * description field in *Clients → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for Clients documents
 */
interface ClientsDocumentData {
  /**
   * Title field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *Clients*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ClientsDocumentDataItemsItem>>;
}

/**
 * Clients document from Prismic
 *
 * - **API ID**: `clients`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientsDocumentData>,
    "clients",
    Lang
  >;

type ContactDocumentDataSlicesSlice =
  | AddressBlockSlice
  | ContactFormSlice
  | ContactBlockSlice
  | HeaderBlockSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Footer → Links 1*
 */
export interface FooterDocumentDataLinks1Item {
  /**
   * link field in *Footer → Links 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_1[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Links 2*
 */
export interface FooterDocumentDataLinks2Item {
  /**
   * Link field in *Footer → Links 2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_2[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Links 3*
 */
export interface FooterDocumentDataLinks3Item {
  /**
   * link field in *Footer → Links 3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_3[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links 1 Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_1_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  links_1_title: prismic.KeyTextField;

  /**
   * Links 1 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_1: prismic.GroupField<Simplify<FooterDocumentDataLinks1Item>>;

  /**
   * Links 2 Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_2_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  links_2_title: prismic.KeyTextField;

  /**
   * Links 2 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_2: prismic.GroupField<Simplify<FooterDocumentDataLinks2Item>>;

  /**
   * Links 3 Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_3_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  links_3_title: prismic.KeyTextField;

  /**
   * Links 3 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_3[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_3: prismic.GroupField<Simplify<FooterDocumentDataLinks3Item>>;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Newsletter Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.newsletter_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_title: prismic.KeyTextField;

  /**
   * Newsletter Message field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.newsletter_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_message: prismic.KeyTextField;

  /**
   * Newsletter Policy field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.newsletter_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_policy: prismic.KeyTextField;

  /**
   * Button Message field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_message: prismic.KeyTextField;

  /**
   * Copyrights field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyrights
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyrights: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ClientsBlockSlice
  | HomeHeroSlice
  | QuoteBlockSlice
  | LinkedInBlockSlice
  | CardsGridSlice
  | VideoBlockSlice
  | IntroBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Video field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NewDocumentDataSlicesSlice =
  | NewTitleSlice
  | NewTextSlice
  | ContactBlockSlice
  | CardsGridSlice;

/**
 * Content for New documents
 */
interface NewDocumentData {
  /**
   * Title field in *New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Title
   * - **API ID Path**: new.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *New*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Date field in *New*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: new.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Category field in *New*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: new.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Highlights" | "Network" | "Insights">;

  /**
   * Team field in *New*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: new.team
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  team: prismic.ContentRelationshipField<"team">;

  /**
   * Slice Zone field in *New*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: new.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewDocumentDataSlicesSlice>;
}

/**
 * New document from Prismic
 *
 * - **API ID**: `new`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewDocumentData>, "new", Lang>;

type NewsDocumentDataSlicesSlice =
  | ContactBlockSlice
  | ArticlesBlockSlice
  | CardsGridSlice
  | HeaderBlockSlice;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NewsDocumentData>, "news", Lang>;

type PortfolioitemDocumentDataSlicesSlice =
  | QuoteBlockSlice
  | ProjectTitleSlice
  | ClientsBlockSlice
  | VideoBlockSlice;

/**
 * Content for PortfolioItem documents
 */
interface PortfolioitemDocumentData {
  /**
   * Title field in *PortfolioItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioitem.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PortfolioItem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioitem.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *PortfolioItem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioitem.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *PortfolioItem*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioitem.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioitemDocumentDataSlicesSlice> /**
   * Meta Title field in *PortfolioItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolioitem.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PortfolioItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolioitem.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PortfolioItem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioitem.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PortfolioItem document from Prismic
 *
 * - **API ID**: `portfolioitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioitemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioitemDocumentData>,
    "portfolioitem",
    Lang
  >;

/**
 * Content for privacy documents
 */
interface PrivacyDocumentData {
  /**
   * Title field in *privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *privacy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * privacy document from Prismic
 *
 * - **API ID**: `privacy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyDocumentData>,
    "privacy",
    Lang
  >;

type ProjectDocumentDataSlicesSlice =
  | ProjectTextSlice
  | ProjectTitleSlice
  | ProjectIntroSlice
  | VideoBlockSlice
  | ClientsBlockSlice
  | QuoteBlockSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Title
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Live Perfomances"
    | "Music Videos"
    | "Live Recordings"
    | "Live Sessions / Music Capture"
  >;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

type ProjectsDocumentDataSlicesSlice =
  | CardsGridSlice
  | ProjectsBlockSlice
  | QuoteBlockSlice
  | HeaderBlockSlice;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: projects.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

type ServicesDocumentDataSlicesSlice =
  | SelectorSlice
  | ClientsBlockSlice
  | QuoteBlockSlice
  | ContactBlockSlice
  | HeaderBlockSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: services.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * URL field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Montreux Media Ventures
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * CTA field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call-To-Action
   * - **API ID Path**: settings.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type SpotlightsDocumentDataSlicesSlice =
  | ProjectTextSlice
  | ClientsBlockSlice
  | ContactBlockSlice
  | HeaderBlockSlice
  | SelectorSlice;

/**
 * Content for Spotlights documents
 */
interface SpotlightsDocumentData {
  /**
   * Title field in *Spotlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlights.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Spotlights*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlights.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SpotlightsDocumentDataSlicesSlice>;
}

/**
 * Spotlights document from Prismic
 *
 * - **API ID**: `spotlights`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpotlightsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SpotlightsDocumentData>,
    "spotlights",
    Lang
  >;

/**
 * Content for Team documents
 */
interface TeamDocumentData {
  /**
   * Name field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Photo field in *Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Job Title field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * LinkedIn URL field in *Team*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.linkedin_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TeamDocumentData>, "team", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | ClientsDocument
  | ContactDocument
  | FooterDocument
  | HomeDocument
  | NewDocument
  | NewsDocument
  | PortfolioitemDocument
  | PrivacyDocument
  | ProjectDocument
  | ProjectsDocument
  | ServicesDocument
  | SettingsDocument
  | SpotlightsDocument
  | TeamDocument;

/**
 * Primary content in *AddressBlock → Default → Primary*
 */
export interface AddressBlockSliceDefaultPrimary {
  /**
   * Title field in *AddressBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Address field in *AddressBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address_block.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Default variation for AddressBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AddressBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AddressBlock*
 */
type AddressBlockSliceVariation = AddressBlockSliceDefault;

/**
 * AddressBlock Shared Slice
 *
 * - **API ID**: `address_block`
 * - **Description**: AddressBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressBlockSlice = prismic.SharedSlice<
  "address_block",
  AddressBlockSliceVariation
>;

/**
 * Primary content in *ArticlesBlock → Default → Primary*
 */
export interface ArticlesBlockSliceDefaultPrimary {
  /**
   * Title field in *ArticlesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ArticlesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticlesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticlesBlock*
 */
type ArticlesBlockSliceVariation = ArticlesBlockSliceDefault;

/**
 * ArticlesBlock Shared Slice
 *
 * - **API ID**: `articles_block`
 * - **Description**: ArticlesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesBlockSlice = prismic.SharedSlice<
  "articles_block",
  ArticlesBlockSliceVariation
>;

/**
 * Item in *CardsGrid → Projects → Primary → Item*
 */
export interface CardsGridSliceDefaultPrimaryItemItem {
  /**
   * Item field in *CardsGrid → Projects → Primary → Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.item[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"new" | "project">;
}

/**
 * Item in *CardsGrid → News → Primary → Item*
 */
export interface CardsGridSliceNewsPrimaryItemItem {
  /**
   * Item field in *CardsGrid → News → Primary → Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.item[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"new">;
}

/**
 * Primary content in *CardsGrid → Projects → Primary*
 */
export interface CardsGridSliceDefaultPrimary {
  /**
   * Title field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Item field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<CardsGridSliceDefaultPrimaryItemItem>>;

  /**
   * Link field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Projects variation for CardsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CardsGrid → News → Primary*
 */
export interface CardsGridSliceNewsPrimary {
  /**
   * Title field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Item field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<CardsGridSliceNewsPrimaryItemItem>>;

  /**
   * Link field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * News variation for CardsGrid Slice
 *
 * - **API ID**: `news`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSliceNews = prismic.SharedSliceVariation<
  "news",
  Simplify<CardsGridSliceNewsPrimary>,
  never
>;

/**
 * Slice variation for *CardsGrid*
 */
type CardsGridSliceVariation = CardsGridSliceDefault | CardsGridSliceNews;

/**
 * CardsGrid Shared Slice
 *
 * - **API ID**: `cards_grid`
 * - **Description**: CardsGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSlice = prismic.SharedSlice<
  "cards_grid",
  CardsGridSliceVariation
>;

/**
 * Default variation for ClientsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ClientsBlock*
 */
type ClientsBlockSliceVariation = ClientsBlockSliceDefault;

/**
 * ClientsBlock Shared Slice
 *
 * - **API ID**: `clients_block`
 * - **Description**: ClientsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsBlockSlice = prismic.SharedSlice<
  "clients_block",
  ClientsBlockSliceVariation
>;

/**
 * Primary content in *ContactBlock → Default → Primary*
 */
export interface ContactBlockSliceDefaultPrimary {
  /**
   * Link field in *ContactBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ContactBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactBlock*
 */
type ContactBlockSliceVariation = ContactBlockSliceDefault;

/**
 * ContactBlock Shared Slice
 *
 * - **API ID**: `contact_block`
 * - **Description**: ContactBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactBlockSlice = prismic.SharedSlice<
  "contact_block",
  ContactBlockSliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → fields*
 */
export interface ContactFormSliceDefaultPrimaryFieldsItem {
  /**
   * PID field in *ContactForm → Default → Primary → fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].pid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pid: prismic.KeyTextField;

  /**
   * label field in *ContactForm → Default → Primary → fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * placeholder field in *ContactForm → Default → Primary → fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Type field in *ContactForm → Default → Primary → fields*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"text" | "email" | "textarea" | "url">;

  /**
   * required field in *ContactForm → Default → Primary → fields*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact_form.default.primary.fields[].required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * fields field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fields: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryFieldsItem>
  >;

  /**
   * success message field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.success_message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  success_message: prismic.RichTextField;

  /**
   * error message	 field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.error_message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  error_message: prismic.RichTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *HeaderBlock → Default → Primary*
 */
export interface HeaderBlockSliceDefaultPrimary {
  /**
   * Title field in *HeaderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeaderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_block.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for HeaderBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderBlock*
 */
type HeaderBlockSliceVariation = HeaderBlockSliceDefault;

/**
 * HeaderBlock Shared Slice
 *
 * - **API ID**: `header_block`
 * - **Description**: HeaderBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSlice = prismic.SharedSlice<
  "header_block",
  HeaderBlockSliceVariation
>;

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Title field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Video field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

/**
 * Primary content in *IntroBlock → Default → Primary*
 */
export interface IntroBlockSliceDefaultPrimary {
  /**
   * Title field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for IntroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroBlock*
 */
type IntroBlockSliceVariation = IntroBlockSliceDefault;

/**
 * IntroBlock Shared Slice
 *
 * - **API ID**: `intro_block`
 * - **Description**: IntroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSlice = prismic.SharedSlice<
  "intro_block",
  IntroBlockSliceVariation
>;

/**
 * Item in *LinkedInBlock → Default → Primary → Items*
 */
export interface LinkedInBlockSliceDefaultPrimaryItemsItem {
  /**
   * Post Url field in *LinkedInBlock → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.items[].post_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  post_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *LinkedInBlock → Default → Primary*
 */
export interface LinkedInBlockSliceDefaultPrimary {
  /**
   * Title field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Items field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<LinkedInBlockSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for LinkedInBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkedInBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkedInBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkedInBlock*
 */
type LinkedInBlockSliceVariation = LinkedInBlockSliceDefault;

/**
 * LinkedInBlock Shared Slice
 *
 * - **API ID**: `linked_in_block`
 * - **Description**: LinkedInBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkedInBlockSlice = prismic.SharedSlice<
  "linked_in_block",
  LinkedInBlockSliceVariation
>;

/**
 * Primary content in *NewText → Default → Primary*
 */
export interface NewTextSliceDefaultPrimary {
  /**
   * Text field in *NewText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for NewText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewText*
 */
type NewTextSliceVariation = NewTextSliceDefault;

/**
 * NewText Shared Slice
 *
 * - **API ID**: `new_text`
 * - **Description**: NewText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewTextSlice = prismic.SharedSlice<
  "new_text",
  NewTextSliceVariation
>;

/**
 * Primary content in *NewTitle → Default → Primary*
 */
export interface NewTitleSliceDefaultPrimary {
  /**
   * Title field in *NewTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for NewTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewTitle*
 */
type NewTitleSliceVariation = NewTitleSliceDefault;

/**
 * NewTitle Shared Slice
 *
 * - **API ID**: `new_title`
 * - **Description**: NewTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewTitleSlice = prismic.SharedSlice<
  "new_title",
  NewTitleSliceVariation
>;

/**
 * Item in *PortfolioBlock → Default → Primary → Items*
 */
export interface PortfolioBlockSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *PortfolioBlock → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_block.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PortfolioBlock → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_block.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video field in *PortfolioBlock → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_block.default.primary.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link field in *PortfolioBlock → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_block.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *PortfolioBlock → Default → Primary*
 */
export interface PortfolioBlockSliceDefaultPrimary {
  /**
   * Items field in *PortfolioBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_block.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<PortfolioBlockSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for PortfolioBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PortfolioBlock*
 */
type PortfolioBlockSliceVariation = PortfolioBlockSliceDefault;

/**
 * PortfolioBlock Shared Slice
 *
 * - **API ID**: `portfolio_block`
 * - **Description**: PortfolioBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioBlockSlice = prismic.SharedSlice<
  "portfolio_block",
  PortfolioBlockSliceVariation
>;

/**
 * Item in *ProjectIntro → Default → Primary → Items*
 */
export interface ProjectIntroSliceDefaultPrimaryItemsItem {
  /**
   * Service Title field in *ProjectIntro → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.items[].service_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_title: prismic.KeyTextField;

  /**
   * Services field in *ProjectIntro → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.items[].services
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  services: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectIntro → Default → Primary*
 */
export interface ProjectIntroSliceDefaultPrimary {
  /**
   * Title field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Details Title field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.details_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  details_title: prismic.KeyTextField;

  /**
   * Items field in *ProjectIntro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_intro.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ProjectIntroSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ProjectIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectIntro*
 */
type ProjectIntroSliceVariation = ProjectIntroSliceDefault;

/**
 * ProjectIntro Shared Slice
 *
 * - **API ID**: `project_intro`
 * - **Description**: ProjectIntro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectIntroSlice = prismic.SharedSlice<
  "project_intro",
  ProjectIntroSliceVariation
>;

/**
 * Primary content in *ProjectText → Default → Primary*
 */
export interface ProjectTextSliceDefaultPrimary {
  /**
   * Description field in *ProjectText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ProjectText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectText*
 */
type ProjectTextSliceVariation = ProjectTextSliceDefault;

/**
 * ProjectText Shared Slice
 *
 * - **API ID**: `project_text`
 * - **Description**: ProjectText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTextSlice = prismic.SharedSlice<
  "project_text",
  ProjectTextSliceVariation
>;

/**
 * Primary content in *ProjectTitle → Default → Primary*
 */
export interface ProjectTitleSliceDefaultPrimary {
  /**
   * Title field in *ProjectTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ProjectTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTitleSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProjectTitle → Left Align → Primary*
 */
export interface ProjectTitleSliceLeftAlignPrimary {
  /**
   * Title field in *ProjectTitle → Left Align → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_title.leftAlign.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Left Align variation for ProjectTitle Slice
 *
 * - **API ID**: `leftAlign`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTitleSliceLeftAlign = prismic.SharedSliceVariation<
  "leftAlign",
  Simplify<ProjectTitleSliceLeftAlignPrimary>,
  never
>;

/**
 * Slice variation for *ProjectTitle*
 */
type ProjectTitleSliceVariation =
  | ProjectTitleSliceDefault
  | ProjectTitleSliceLeftAlign;

/**
 * ProjectTitle Shared Slice
 *
 * - **API ID**: `project_title`
 * - **Description**: ProjectTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTitleSlice = prismic.SharedSlice<
  "project_title",
  ProjectTitleSliceVariation
>;

/**
 * Default variation for ProjectsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectsBlock*
 */
type ProjectsBlockSliceVariation = ProjectsBlockSliceDefault;

/**
 * ProjectsBlock Shared Slice
 *
 * - **API ID**: `projects_block`
 * - **Description**: ProjectsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsBlockSlice = prismic.SharedSlice<
  "projects_block",
  ProjectsBlockSliceVariation
>;

/**
 * Primary content in *QuoteBlock → Default → Primary*
 */
export interface QuoteBlockSliceDefaultPrimary {
  /**
   * Title field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for QuoteBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteBlock*
 */
type QuoteBlockSliceVariation = QuoteBlockSliceDefault;

/**
 * QuoteBlock Shared Slice
 *
 * - **API ID**: `quote_block`
 * - **Description**: QuoteBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSlice = prismic.SharedSlice<
  "quote_block",
  QuoteBlockSliceVariation
>;

/**
 * Item in *Selector → Default → Primary → Items*
 */
export interface SelectorSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *Selector → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: selector.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"portfolioitem">;
}

/**
 * Primary content in *Selector → Default → Primary*
 */
export interface SelectorSliceDefaultPrimary {
  /**
   * Title field in *Selector → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: selector.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *Selector → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: selector.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<SelectorSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Selector Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelectorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SelectorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Selector*
 */
type SelectorSliceVariation = SelectorSliceDefault;

/**
 * Selector Shared Slice
 *
 * - **API ID**: `selector`
 * - **Description**: Selector
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelectorSlice = prismic.SharedSlice<
  "selector",
  SelectorSliceVariation
>;

/**
 * Item in *TeamBlock → Default → Primary → Items*
 */
export interface TeamBlockSliceDefaultPrimaryItemsItem {
  /**
   * Team member field in *TeamBlock → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.default.primary.items[].team_member
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  team_member: prismic.ContentRelationshipField<"team">;
}

/**
 * Primary content in *TeamBlock → Default → Primary*
 */
export interface TeamBlockSliceDefaultPrimary {
  /**
   * Title field in *TeamBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *TeamBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamBlockSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for TeamBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamBlock*
 */
type TeamBlockSliceVariation = TeamBlockSliceDefault;

/**
 * TeamBlock Shared Slice
 *
 * - **API ID**: `team_block`
 * - **Description**: TeamBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamBlockSlice = prismic.SharedSlice<
  "team_block",
  TeamBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Video field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      ClientsDocument,
      ClientsDocumentData,
      ClientsDocumentDataItemsItem,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinks1Item,
      FooterDocumentDataLinks2Item,
      FooterDocumentDataLinks3Item,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NewDocument,
      NewDocumentData,
      NewDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      PortfolioitemDocument,
      PortfolioitemDocumentData,
      PortfolioitemDocumentDataSlicesSlice,
      PrivacyDocument,
      PrivacyDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SpotlightsDocument,
      SpotlightsDocumentData,
      SpotlightsDocumentDataSlicesSlice,
      TeamDocument,
      TeamDocumentData,
      AllDocumentTypes,
      AddressBlockSlice,
      AddressBlockSliceDefaultPrimary,
      AddressBlockSliceVariation,
      AddressBlockSliceDefault,
      ArticlesBlockSlice,
      ArticlesBlockSliceDefaultPrimary,
      ArticlesBlockSliceVariation,
      ArticlesBlockSliceDefault,
      CardsGridSlice,
      CardsGridSliceDefaultPrimaryItemItem,
      CardsGridSliceDefaultPrimary,
      CardsGridSliceNewsPrimaryItemItem,
      CardsGridSliceNewsPrimary,
      CardsGridSliceVariation,
      CardsGridSliceDefault,
      CardsGridSliceNews,
      ClientsBlockSlice,
      ClientsBlockSliceVariation,
      ClientsBlockSliceDefault,
      ContactBlockSlice,
      ContactBlockSliceDefaultPrimary,
      ContactBlockSliceVariation,
      ContactBlockSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryFieldsItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      HeaderBlockSlice,
      HeaderBlockSliceDefaultPrimary,
      HeaderBlockSliceVariation,
      HeaderBlockSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      IntroBlockSlice,
      IntroBlockSliceDefaultPrimary,
      IntroBlockSliceVariation,
      IntroBlockSliceDefault,
      LinkedInBlockSlice,
      LinkedInBlockSliceDefaultPrimaryItemsItem,
      LinkedInBlockSliceDefaultPrimary,
      LinkedInBlockSliceVariation,
      LinkedInBlockSliceDefault,
      NewTextSlice,
      NewTextSliceDefaultPrimary,
      NewTextSliceVariation,
      NewTextSliceDefault,
      NewTitleSlice,
      NewTitleSliceDefaultPrimary,
      NewTitleSliceVariation,
      NewTitleSliceDefault,
      PortfolioBlockSlice,
      PortfolioBlockSliceDefaultPrimaryItemsItem,
      PortfolioBlockSliceDefaultPrimary,
      PortfolioBlockSliceVariation,
      PortfolioBlockSliceDefault,
      ProjectIntroSlice,
      ProjectIntroSliceDefaultPrimaryItemsItem,
      ProjectIntroSliceDefaultPrimary,
      ProjectIntroSliceVariation,
      ProjectIntroSliceDefault,
      ProjectTextSlice,
      ProjectTextSliceDefaultPrimary,
      ProjectTextSliceVariation,
      ProjectTextSliceDefault,
      ProjectTitleSlice,
      ProjectTitleSliceDefaultPrimary,
      ProjectTitleSliceLeftAlignPrimary,
      ProjectTitleSliceVariation,
      ProjectTitleSliceDefault,
      ProjectTitleSliceLeftAlign,
      ProjectsBlockSlice,
      ProjectsBlockSliceVariation,
      ProjectsBlockSliceDefault,
      QuoteBlockSlice,
      QuoteBlockSliceDefaultPrimary,
      QuoteBlockSliceVariation,
      QuoteBlockSliceDefault,
      SelectorSlice,
      SelectorSliceDefaultPrimaryItemsItem,
      SelectorSliceDefaultPrimary,
      SelectorSliceVariation,
      SelectorSliceDefault,
      TeamBlockSlice,
      TeamBlockSliceDefaultPrimaryItemsItem,
      TeamBlockSliceDefaultPrimary,
      TeamBlockSliceVariation,
      TeamBlockSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
