// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | QuoteBlockSlice
  | LinkedInBlockSlice
  | CardsGridSlice
  | VideoBlockSlice
  | IntroBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Video field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NewDocumentDataSlicesSlice = never;

/**
 * Content for New documents
 */
interface NewDocumentData {
  /**
   * Title field in *New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Title
   * - **API ID Path**: new.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *New*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Date field in *New*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: new.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Category field in *New*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: new.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Highlights" | "Network" | "Insights">;

  /**
   * Slice Zone field in *New*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: new.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewDocumentDataSlicesSlice>;
}

/**
 * New document from Prismic
 *
 * - **API ID**: `new`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewDocumentData>, "new", Lang>;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Title
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Live Perfomances" | "Music Videos">;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: projects.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: services.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * URL field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Montreux Media Ventures
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * CTA field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call-To-Action
   * - **API ID Path**: settings.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | FooterDocument
  | HomeDocument
  | NewDocument
  | NewsDocument
  | ProjectDocument
  | ProjectsDocument
  | ServicesDocument
  | SettingsDocument;

/**
 * Item in *CardsBlock → Default → Primary → Cards*
 */
export interface CardsBlockSliceDefaultPrimaryCardsItem {
  /**
   * Link field in *CardsBlock → Default → Primary → Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_block.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"new" | "projects">;
}

/**
 * Primary content in *CardsBlock → Default → Primary*
 */
export interface CardsBlockSliceDefaultPrimary {
  /**
   * Title field in *CardsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Block Title
   * - **API ID Path**: cards_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Cards field in *CardsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_block.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<CardsBlockSliceDefaultPrimaryCardsItem>>;

  /**
   * Link field in *CardsBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Block Link
   * - **API ID Path**: cards_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CardsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardsBlock*
 */
type CardsBlockSliceVariation = CardsBlockSliceDefault;

/**
 * CardsBlock Shared Slice
 *
 * - **API ID**: `cards_block`
 * - **Description**: CardsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsBlockSlice = prismic.SharedSlice<
  "cards_block",
  CardsBlockSliceVariation
>;

/**
 * Item in *CardsGrid → Projects → Primary → Item*
 */
export interface CardsGridSliceDefaultPrimaryItemItem {
  /**
   * Item field in *CardsGrid → Projects → Primary → Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.item[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"new">;
}

/**
 * Item in *CardsGrid → News → Primary → Item*
 */
export interface CardsGridSliceNewsPrimaryItemItem {
  /**
   * Item field in *CardsGrid → News → Primary → Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.item[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"new">;
}

/**
 * Primary content in *CardsGrid → Projects → Primary*
 */
export interface CardsGridSliceDefaultPrimary {
  /**
   * Title field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Item field in *CardsGrid → Projects → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<CardsGridSliceDefaultPrimaryItemItem>>;
}

/**
 * Projects variation for CardsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CardsGrid → News → Primary*
 */
export interface CardsGridSliceNewsPrimary {
  /**
   * Title field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Item field in *CardsGrid → News → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_grid.news.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<CardsGridSliceNewsPrimaryItemItem>>;
}

/**
 * News variation for CardsGrid Slice
 *
 * - **API ID**: `news`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSliceNews = prismic.SharedSliceVariation<
  "news",
  Simplify<CardsGridSliceNewsPrimary>,
  never
>;

/**
 * Slice variation for *CardsGrid*
 */
type CardsGridSliceVariation = CardsGridSliceDefault | CardsGridSliceNews;

/**
 * CardsGrid Shared Slice
 *
 * - **API ID**: `cards_grid`
 * - **Description**: CardsGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSlice = prismic.SharedSlice<
  "cards_grid",
  CardsGridSliceVariation
>;

/**
 * Primary content in *IntroBlock → Default → Primary*
 */
export interface IntroBlockSliceDefaultPrimary {
  /**
   * Title field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for IntroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroBlock*
 */
type IntroBlockSliceVariation = IntroBlockSliceDefault;

/**
 * IntroBlock Shared Slice
 *
 * - **API ID**: `intro_block`
 * - **Description**: IntroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSlice = prismic.SharedSlice<
  "intro_block",
  IntroBlockSliceVariation
>;

/**
 * Item in *LinkedInBlock → Default → Primary → Items*
 */
export interface LinkedInBlockSliceDefaultPrimaryItemsItem {
  /**
   * Post Url field in *LinkedInBlock → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.items[].post_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  post_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *LinkedInBlock → Default → Primary*
 */
export interface LinkedInBlockSliceDefaultPrimary {
  /**
   * Title field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Items field in *LinkedInBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: linked_in_block.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<LinkedInBlockSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for LinkedInBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkedInBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkedInBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkedInBlock*
 */
type LinkedInBlockSliceVariation = LinkedInBlockSliceDefault;

/**
 * LinkedInBlock Shared Slice
 *
 * - **API ID**: `linked_in_block`
 * - **Description**: LinkedInBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkedInBlockSlice = prismic.SharedSlice<
  "linked_in_block",
  LinkedInBlockSliceVariation
>;

/**
 * Primary content in *QuoteBlock → Default → Primary*
 */
export interface QuoteBlockSliceDefaultPrimary {
  /**
   * Title field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for QuoteBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteBlock*
 */
type QuoteBlockSliceVariation = QuoteBlockSliceDefault;

/**
 * QuoteBlock Shared Slice
 *
 * - **API ID**: `quote_block`
 * - **Description**: QuoteBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSlice = prismic.SharedSlice<
  "quote_block",
  QuoteBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Video field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      ContactDocument,
      ContactDocumentData,
      FooterDocument,
      FooterDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NewDocument,
      NewDocumentData,
      NewDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectsDocument,
      ProjectsDocumentData,
      ServicesDocument,
      ServicesDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      CardsBlockSlice,
      CardsBlockSliceDefaultPrimaryCardsItem,
      CardsBlockSliceDefaultPrimary,
      CardsBlockSliceVariation,
      CardsBlockSliceDefault,
      CardsGridSlice,
      CardsGridSliceDefaultPrimaryItemItem,
      CardsGridSliceDefaultPrimary,
      CardsGridSliceNewsPrimaryItemItem,
      CardsGridSliceNewsPrimary,
      CardsGridSliceVariation,
      CardsGridSliceDefault,
      CardsGridSliceNews,
      IntroBlockSlice,
      IntroBlockSliceDefaultPrimary,
      IntroBlockSliceVariation,
      IntroBlockSliceDefault,
      LinkedInBlockSlice,
      LinkedInBlockSliceDefaultPrimaryItemsItem,
      LinkedInBlockSliceDefaultPrimary,
      LinkedInBlockSliceVariation,
      LinkedInBlockSliceDefault,
      QuoteBlockSlice,
      QuoteBlockSliceDefaultPrimary,
      QuoteBlockSliceVariation,
      QuoteBlockSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
