// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  address_block: defineAsyncComponent(() => import("./AddressBlock/index.vue")),
  articles_block: defineAsyncComponent(
    () => import("./ArticlesBlock/index.vue"),
  ),
  cards_grid: defineAsyncComponent(() => import("./CardsGrid/index.vue")),
  clients_block: defineAsyncComponent(() => import("./ClientsBlock/index.vue")),
  contact_block: defineAsyncComponent(() => import("./ContactBlock/index.vue")),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  header_block: defineAsyncComponent(() => import("./HeaderBlock/index.vue")),
  intro_block: defineAsyncComponent(() => import("./IntroBlock/index.vue")),
  linked_in_block: defineAsyncComponent(
    () => import("./LinkedInBlock/index.vue"),
  ),
  new_text: defineAsyncComponent(() => import("./NewText/index.vue")),
  new_title: defineAsyncComponent(() => import("./NewTitle/index.vue")),
  portfolio_block: defineAsyncComponent(
    () => import("./PortfolioBlock/index.vue"),
  ),
  project_hero: defineAsyncComponent(() => import("./ProjectHero/index.vue")),
  project_intro: defineAsyncComponent(() => import("./ProjectIntro/index.vue")),
  project_text: defineAsyncComponent(() => import("./ProjectText/index.vue")),
  project_title: defineAsyncComponent(() => import("./ProjectTitle/index.vue")),
  projects_block: defineAsyncComponent(
    () => import("./ProjectsBlock/index.vue"),
  ),
  quote_block: defineAsyncComponent(() => import("./QuoteBlock/index.vue")),
  team_block: defineAsyncComponent(() => import("./TeamBlock/index.vue")),
  video_block: defineAsyncComponent(() => import("./VideoBlock/index.vue")),
});
