// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  cards_block: defineAsyncComponent(() => import("./CardsBlock/index.vue")),
  cards_grid: defineAsyncComponent(() => import("./CardsGrid/index.vue")),
  header_block: defineAsyncComponent(() => import("./HeaderBlock/index.vue")),
  intro_block: defineAsyncComponent(() => import("./IntroBlock/index.vue")),
  linked_in_block: defineAsyncComponent(
    () => import("./LinkedInBlock/index.vue"),
  ),
  quote_block: defineAsyncComponent(() => import("./QuoteBlock/index.vue")),
  video_block: defineAsyncComponent(() => import("./VideoBlock/index.vue")),
});
